$(document).ready(function(){
$('h3.class-and-level').text(" Rogue"+": "+"3");
$('h2.class-and-level').text(" Rogue"+": "+"3");
$('#strength').append("13");
$('#dexterity').append("13");
$('#constitution').append("14");
$('#intelligence').append("11");
$('#wisdom').append("9");
$('#charisma').append("14");
$('#acrobatics').append("1");
$('#animal-handling').append("-1");
$('#arcana').append("0");
$('#athletics').append("1");
$('#deception').append("2");
$('#history').append("0");
$('#insight').append("-1");
$('#intimidation').append("2");
$('#investigation').append("0");
$('#medicine').append("-1");
$('#nature').append("0");
$('#perception').append("-1");
$('#performance').append("2");
$('#persuasion').append("2");
$('#religion').append("0");
$('#sleight-of-hand').append("1");
$('#stealth').append("1");
$('#survival').append("-1");
$('#personalityTrait').append("I place no stock in wealthy or well-mannered folk. Money and manners won't save you from a hungry owlbear.");
$('#ideal').append("Greater Good. It is each perons's responsibility to make the most happiness for the whole tribe.");
$('#bond').append("An injury to the unspoiled wilderness of my home is an injury to me.");
$('#flaw').append("I am slow to trust members of other races, tribes, and societies.");
$('#proficiencies').html("<li>Armor: Light</li><li>Language: Common</li><li>Language: Draconic</li><li>Saving Throw: Dexterity</li><li>Saving Throw: Intelligence</li><li>Skill: Intimidation</li><li>Skill: Investigation</li><li>Skill: Performance</li><li>Skill: Persuasion</li><li>Tool: Thieve's Tools</li><li>Weapon: Hand Crossbows</li><li>Weapon: Longswords</li><li>Weapon: Rapiers</li><li>Weapon: Shortswords</li><li>Weapons: Simple</li>");
$('#features').html("<li>Breath Weapon</li><li>Cunning Action</li><li>Damage Resistance</li><li>Draconic Ancestry</li><li>Expertise</li><li>Fast Hands</li><li>Roguish Archtype</li><li>Second-Story Work</li><li>Sneak Attack</li><li>Theives' Cant</li>");
$('#equipment').html("<li>Burglar's Pack</li><li>Dagger</li><li>Dagger</li><li>Leather Armor</li><li>Shortsword</li><li>Shortsword</li><li>Thieve's Tools</li><li> Copper: 0</li><li> Silver: 0</li><li> Electrum: 0</li><li> Gold: 0</li><li> Platinum: 10</li>");});